import type { ResearchReport, Workflow } from "@/lib/types"

export const DASHBOARD_STATS = {
  activeWorkflows: 3,
  completedResearch: 128,
  sourcesAnalyzed: 2481,
  reportsGenerated: 86,
}

export const INITIAL_WORKFLOWS: Workflow[] = [
  {
    id: "research_8f31a2",
    title: "Stripe vs Adyen vs Paddle",
    objective: "Compare Stripe, Adyen, and Paddle for a SaaS startup.",
    instructions:
      "Focus on transaction fees, payout speed, and support for usage-based billing.",
    status: "running",
    sourcesCount: 18,
    startedLabel: "12 min ago",
    durationLabel: "—",
    progress: 68,
    steps: [
      {
        id: "plan",
        name: "Research plan generated",
        status: "completed",
        timestamp: "19:08:21",
        duration: "1s",
        description: "Broke the objective into 7 research steps across 3 vendors.",
      },
      {
        id: "queries",
        name: "Search queries generated",
        status: "completed",
        timestamp: "19:08:22",
        duration: "2s",
        description: "Generated 9 targeted search queries via Exa.",
      },
      {
        id: "stripe",
        name: "Stripe research",
        status: "completed",
        timestamp: "19:08:25",
        duration: "42s",
        description: "Collected and analyzed 8 relevant sources.",
      },
      {
        id: "adyen",
        name: "Adyen research",
        status: "completed",
        timestamp: "19:08:29",
        duration: "38s",
        description: "Collected and analyzed 6 relevant sources.",
      },
      {
        id: "compare",
        name: "Comparing pricing",
        status: "running",
        timestamp: "19:08:31",
        description: "Extracting transaction fees and monthly pricing across vendors.",
      },
      {
        id: "fact-check",
        name: "Fact checking",
        status: "pending",
      },
      {
        id: "report",
        name: "Generate final report",
        status: "pending",
      },
    ],
    activities: [
      { id: "a1", timestamp: "19:08:21", event: "workflow.started" },
      { id: "a2", timestamp: "19:08:22", event: "research.plan_generated" },
      { id: "a3", timestamp: "19:08:23", event: "exa.search_started" },
      {
        id: "a4",
        timestamp: "19:08:25",
        event: "exa.sources_found",
        detail: "12 sources",
      },
      { id: "a5", timestamp: "19:08:27", event: "stripe.analysis_done" },
      { id: "a6", timestamp: "19:08:29", event: "adyen.analysis_done" },
      { id: "a7", timestamp: "19:08:31", event: "comparison.started" },
      {
        id: "a8",
        timestamp: "19:08:34",
        event: "comparison.sources_processed",
        detail: "8 / 12",
      },
    ],
    sources: [
      {
        id: "s1",
        title: "Stripe Pricing",
        domain: "stripe.com",
        type: "primary",
        relevance: 98,
        status: "analyzed",
        addedAt: "19:08:24",
      },
      {
        id: "s2",
        title: "Adyen Pricing",
        domain: "adyen.com",
        type: "primary",
        relevance: 96,
        status: "analyzed",
        addedAt: "19:08:28",
      },
      {
        id: "s3",
        title: "Paddle Pricing",
        domain: "paddle.com",
        type: "primary",
        relevance: 94,
        status: "analyzing",
        addedAt: "19:08:31",
      },
      {
        id: "s4",
        title: "Stripe vs Adyen: a payments infrastructure comparison",
        domain: "highperformance.dev",
        type: "secondary",
        relevance: 87,
        status: "analyzed",
        addedAt: "19:08:25",
      },
      {
        id: "s5",
        title: "Paddle vs Stripe for SaaS billing",
        domain: "paddle.com",
        type: "secondary",
        relevance: 82,
        status: "queued",
        addedAt: "19:08:32",
      },
      {
        id: "s6",
        title: "Merchant of record explained",
        domain: "baremetrics.com",
        type: "reference",
        relevance: 74,
        status: "queued",
        addedAt: "19:08:32",
      },
    ],
    agentActivity: {
      currentStatus: "Analyzing pricing information across primary sources.",
      taskLabel: "Searching primary sources",
      taskDescription: "Extract transaction fees and monthly pricing.",
      sourcesProcessed: 8,
      sourcesTotal: 12,
      progress: 72,
    },
  },
  {
    id: "research_5c9e14",
    title: "Stripe vs Adyen",
    objective: "Compare Stripe and Adyen for a mid-market SaaS company.",
    status: "completed",
    sourcesCount: 24,
    startedLabel: "2 min ago",
    durationLabel: "04:32",
    progress: 100,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "18:41:02", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "completed", timestamp: "18:41:03", duration: "2s" },
      { id: "stripe", name: "Stripe research", status: "completed", timestamp: "18:41:06", duration: "48s", description: "Collected and analyzed 12 relevant sources." },
      { id: "adyen", name: "Adyen research", status: "completed", timestamp: "18:41:54", duration: "51s", description: "Collected and analyzed 11 relevant sources." },
      { id: "compare", name: "Comparing pricing", status: "completed", timestamp: "18:42:45", duration: "1m 12s" },
      { id: "fact-check", name: "Fact checking", status: "completed", timestamp: "18:43:57", duration: "22s" },
      { id: "report", name: "Generate final report", status: "completed", timestamp: "18:44:19", duration: "13s", description: "Report ready with 24 cited sources." },
    ],
    activities: [
      { id: "a1", timestamp: "18:41:02", event: "workflow.started" },
      { id: "a2", timestamp: "18:41:03", event: "research.plan_generated" },
      { id: "a3", timestamp: "18:41:04", event: "exa.search_started" },
      { id: "a4", timestamp: "18:41:06", event: "exa.sources_found", detail: "18 sources" },
      { id: "a5", timestamp: "18:41:54", event: "stripe.analysis_done" },
      { id: "a6", timestamp: "18:42:45", event: "adyen.analysis_done" },
      { id: "a7", timestamp: "18:43:57", event: "comparison.done" },
      { id: "a8", timestamp: "18:44:19", event: "report.generated" },
      { id: "a9", timestamp: "18:44:32", event: "workflow.completed" },
    ],
    sources: [
      { id: "s1", title: "Stripe Pricing", domain: "stripe.com", type: "primary", relevance: 98, status: "analyzed", addedAt: "18:41:10" },
      { id: "s2", title: "Adyen Pricing", domain: "adyen.com", type: "primary", relevance: 95, status: "analyzed", addedAt: "18:41:56" },
      { id: "s3", title: "Stripe vs Adyen: enterprise checklist", domain: "g2.com", type: "secondary", relevance: 88, status: "analyzed", addedAt: "18:41:40" },
      { id: "s4", title: "Adyen platform overview", domain: "adyen.com", type: "primary", relevance: 90, status: "analyzed", addedAt: "18:42:01" },
      { id: "s5", title: "Payment orchestration explained", domain: "a16z.com", type: "reference", relevance: 71, status: "analyzed", addedAt: "18:42:20" },
    ],
  },
  {
    id: "research_2a77d0",
    title: "AI infrastructure landscape",
    objective: "Map the current AI infrastructure and tooling landscape.",
    status: "running",
    sourcesCount: 18,
    startedLabel: "8 min ago",
    durationLabel: "—",
    progress: 41,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "19:02:10", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "completed", timestamp: "19:02:11", duration: "2s" },
      { id: "vendors", name: "Vendor landscape mapped", status: "completed", timestamp: "19:02:44", duration: "33s", description: "Identified 14 relevant infrastructure vendors." },
      { id: "funding", name: "Funding and market data collected", status: "running", timestamp: "19:03:20", description: "Gathering funding rounds and market sizing data." },
      { id: "compare", name: "Comparing capabilities", status: "pending" },
      { id: "fact-check", name: "Fact checking", status: "pending" },
      { id: "report", name: "Generate final report", status: "pending" },
    ],
    activities: [
      { id: "a1", timestamp: "19:02:10", event: "workflow.started" },
      { id: "a2", timestamp: "19:02:11", event: "research.plan_generated" },
      { id: "a3", timestamp: "19:02:12", event: "exa.search_started" },
      { id: "a4", timestamp: "19:02:44", event: "exa.sources_found", detail: "18 sources" },
      { id: "a5", timestamp: "19:03:20", event: "market_data.collection_started" },
    ],
    sources: [
      { id: "s1", title: "State of AI infrastructure 2026", domain: "a16z.com", type: "primary", relevance: 96, status: "analyzed", addedAt: "19:02:40" },
      { id: "s2", title: "Compute orchestration vendor map", domain: "crunchbase.com", type: "secondary", relevance: 84, status: "analyzed", addedAt: "19:02:45" },
      { id: "s3", title: "Durable execution engines compared", domain: "temporal.io", type: "primary", relevance: 91, status: "analyzing", addedAt: "19:03:05" },
      { id: "s4", title: "Vector database landscape", domain: "a16z.com", type: "secondary", relevance: 79, status: "queued", addedAt: "19:03:22" },
    ],
    agentActivity: {
      currentStatus: "Collecting funding and market sizing data across vendors.",
      taskLabel: "Gathering market data",
      taskDescription: "Cross-reference funding rounds with public market estimates.",
      sourcesProcessed: 6,
      sourcesTotal: 18,
      progress: 34,
    },
  },
  {
    id: "research_ff10b3",
    title: "OpenAI competitors",
    objective: "Identify and profile OpenAI's closest competitors.",
    status: "completed",
    sourcesCount: 31,
    startedLabel: "Yesterday",
    durationLabel: "06:18",
    progress: 100,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "14:02:01", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "completed", timestamp: "14:02:02", duration: "3s" },
      { id: "landscape", name: "Competitor landscape mapped", status: "completed", timestamp: "14:03:10", duration: "1m 8s" },
      { id: "profiles", name: "Company profiles researched", status: "completed", timestamp: "14:05:40", duration: "2m 30s" },
      { id: "compare", name: "Comparing positioning", status: "completed", timestamp: "14:07:15", duration: "1m 35s" },
      { id: "fact-check", name: "Fact checking", status: "completed", timestamp: "14:08:02", duration: "47s" },
      { id: "report", name: "Generate final report", status: "completed", timestamp: "14:08:19", duration: "17s" },
    ],
    activities: [
      { id: "a1", timestamp: "14:02:01", event: "workflow.started" },
      { id: "a2", timestamp: "14:02:02", event: "research.plan_generated" },
      { id: "a3", timestamp: "14:03:10", event: "exa.sources_found", detail: "31 sources" },
      { id: "a4", timestamp: "14:07:15", event: "comparison.done" },
      { id: "a5", timestamp: "14:08:19", event: "report.generated" },
      { id: "a6", timestamp: "14:08:22", event: "workflow.completed" },
    ],
    sources: [
      { id: "s1", title: "Anthropic company overview", domain: "anthropic.com", type: "primary", relevance: 97, status: "analyzed", addedAt: "14:03:12" },
      { id: "s2", title: "Google DeepMind research index", domain: "deepmind.google", type: "primary", relevance: 93, status: "analyzed", addedAt: "14:03:30" },
      { id: "s3", title: "Mistral AI funding history", domain: "crunchbase.com", type: "secondary", relevance: 85, status: "analyzed", addedAt: "14:04:02" },
      { id: "s4", title: "Frontier model leaderboard", domain: "lmarena.ai", type: "reference", relevance: 88, status: "analyzed", addedAt: "14:04:40" },
    ],
  },
  {
    id: "research_c410a9",
    title: "Payment gateway pricing",
    objective: "Survey pricing models across major payment gateways.",
    status: "waiting",
    sourcesCount: 12,
    startedLabel: "Yesterday",
    durationLabel: "—",
    progress: 8,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "09:14:02", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "pending" },
      { id: "survey", name: "Gateway pricing surveyed", status: "pending" },
      { id: "compare", name: "Comparing pricing models", status: "pending" },
      { id: "fact-check", name: "Fact checking", status: "pending" },
      { id: "report", name: "Generate final report", status: "pending" },
    ],
    activities: [
      { id: "a1", timestamp: "09:14:02", event: "workflow.started" },
      { id: "a2", timestamp: "09:14:03", event: "research.plan_generated" },
      { id: "a3", timestamp: "09:14:05", event: "workflow.queued", detail: "waiting for available agent" },
    ],
    sources: [
      { id: "s1", title: "Braintree pricing", domain: "braintreepayments.com", type: "primary", relevance: 90, status: "queued", addedAt: "09:14:04" },
      { id: "s2", title: "Checkout.com pricing", domain: "checkout.com", type: "primary", relevance: 89, status: "queued", addedAt: "09:14:04" },
    ],
    agentActivity: {
      currentStatus: "Queued — waiting for an available research agent.",
      taskLabel: "In queue",
      taskDescription: "Workflow will resume automatically once an agent is free.",
      sourcesProcessed: 0,
      sourcesTotal: 12,
      progress: 0,
    },
  },
  {
    id: "research_71bd4e",
    title: "Salesforce vs HubSpot pricing",
    objective: "Compare Salesforce and HubSpot pricing for a Series B startup.",
    status: "failed",
    sourcesCount: 6,
    startedLabel: "3 days ago",
    durationLabel: "01:47",
    progress: 34,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "11:20:01", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "completed", timestamp: "11:20:03", duration: "2s" },
      { id: "salesforce", name: "Salesforce research", status: "completed", timestamp: "11:20:45", duration: "42s" },
      { id: "hubspot", name: "HubSpot research", status: "failed", timestamp: "11:21:48", duration: "—", description: "Source fetch failed after 3 retries: rate limited by target site." },
      { id: "compare", name: "Comparing pricing", status: "pending" },
      { id: "fact-check", name: "Fact checking", status: "pending" },
      { id: "report", name: "Generate final report", status: "pending" },
    ],
    activities: [
      { id: "a1", timestamp: "11:20:01", event: "workflow.started" },
      { id: "a2", timestamp: "11:20:45", event: "salesforce.analysis_done" },
      { id: "a3", timestamp: "11:21:12", event: "hubspot.fetch_retry", detail: "attempt 1/3" },
      { id: "a4", timestamp: "11:21:30", event: "hubspot.fetch_retry", detail: "attempt 2/3" },
      { id: "a5", timestamp: "11:21:48", event: "hubspot.fetch_failed", detail: "rate limited" },
      { id: "a6", timestamp: "11:21:49", event: "workflow.failed" },
    ],
    sources: [
      { id: "s1", title: "Salesforce Sales Cloud pricing", domain: "salesforce.com", type: "primary", relevance: 95, status: "analyzed", addedAt: "11:20:20" },
      { id: "s2", title: "HubSpot pricing", domain: "hubspot.com", type: "primary", relevance: 0, status: "failed", addedAt: "11:21:48" },
    ],
  },
  {
    id: "research_9e02f5",
    title: "Crypto payment processors",
    objective: "Evaluate crypto payment processors for e-commerce checkout.",
    status: "cancelled",
    sourcesCount: 4,
    startedLabel: "4 days ago",
    durationLabel: "00:52",
    progress: 22,
    steps: [
      { id: "plan", name: "Research plan generated", status: "completed", timestamp: "16:44:10", duration: "1s" },
      { id: "queries", name: "Search queries generated", status: "completed", timestamp: "16:44:12", duration: "2s" },
      { id: "survey", name: "Provider landscape surveyed", status: "pending", description: "Cancelled before this step started." },
      { id: "compare", name: "Comparing providers", status: "pending" },
      { id: "fact-check", name: "Fact checking", status: "pending" },
      { id: "report", name: "Generate final report", status: "pending" },
    ],
    activities: [
      { id: "a1", timestamp: "16:44:10", event: "workflow.started" },
      { id: "a2", timestamp: "16:44:12", event: "research.plan_generated" },
      { id: "a3", timestamp: "16:45:02", event: "workflow.cancelled", detail: "cancelled by user" },
    ],
    sources: [
      { id: "s1", title: "Coinbase Commerce docs", domain: "coinbase.com", type: "primary", relevance: 80, status: "queued", addedAt: "16:44:30" },
    ],
  },
]

const DASHBOARD_ORDER = [
  "research_5c9e14",
  "research_2a77d0",
  "research_ff10b3",
  "research_c410a9",
  "research_8f31a2",
  "research_71bd4e",
  "research_9e02f5",
]

INITIAL_WORKFLOWS.sort(
  (a, b) => DASHBOARD_ORDER.indexOf(a.id) - DASHBOARD_ORDER.indexOf(b.id)
)

export const REPORTS: ResearchReport[] = [
  {
    id: "report_1",
    title: "Stripe vs Adyen vs Paddle",
    description: "Payment infrastructure comparison",
    category: "Payments",
    status: "ready",
    sourceCount: 24,
    createdLabel: "Generated today",
    workflowId: "research_5c9e14",
  },
  {
    id: "report_2",
    title: "AI infrastructure landscape",
    description: "Market research",
    category: "Market research",
    status: "ready",
    sourceCount: 18,
    createdLabel: "Generated yesterday",
    workflowId: "research_2a77d0",
  },
  {
    id: "report_3",
    title: "OpenAI competitors",
    description: "Competitive analysis",
    category: "Competitive analysis",
    status: "ready",
    sourceCount: 31,
    createdLabel: "Generated Aug 28",
    workflowId: "research_ff10b3",
  },
]

let workflowCounter = 0

export function generateWorkflowId() {
  workflowCounter += 1
  return `research_${Date.now().toString(16).slice(-6)}${workflowCounter}`
}
